# Generated by Django 3.1 on 2020-08-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200831_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.student'),
        ),
    ]